-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.pagamento
(
    "IDPagamento" serial NOT NULL,
    "IDPrenotazione" integer,
    "Importo" numeric(10, 2),
    "Stato" character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT pagamento_pkey PRIMARY KEY ("IDPagamento")
);

CREATE TABLE IF NOT EXISTS public.passeggero
(
    role boolean,
    idutente integer NOT NULL,
    email character varying(20) COLLATE pg_catalog."default",
    nome character varying(20) COLLATE pg_catalog."default",
    password character varying(20) COLLATE pg_catalog."default",
    surname character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT passeggero_pkey PRIMARY KEY (idutente)
);

CREATE TABLE IF NOT EXISTS public.prenotazione
(
    "IDPrenotazione" serial NOT NULL,
    "DataOra" timestamp without time zone,
    "Stato" character varying(20) COLLATE pg_catalog."default",
    "IDTaxi" integer,
    idpasseggero integer,
    idtassista integer,
    CONSTRAINT prenotazione_pkey PRIMARY KEY ("IDPrenotazione")
);

CREATE TABLE IF NOT EXISTS public.recensione
(
    "IDRecensione" serial NOT NULL,
    "IDPrenotazione" integer,
    "Testo" text COLLATE pg_catalog."default",
    "Valutazione" integer,
    CONSTRAINT recensione_pkey PRIMARY KEY ("IDRecensione")
);

CREATE TABLE IF NOT EXISTS public.tassista
(
    role boolean,
    idutente integer NOT NULL,
    email character varying(20) COLLATE pg_catalog."default",
    nome character varying(20) COLLATE pg_catalog."default",
    password character varying(20) COLLATE pg_catalog."default",
    surname character varying(20) COLLATE pg_catalog."default",
    targataxi character varying(6) COLLATE pg_catalog."default",
    CONSTRAINT tassista_pkey PRIMARY KEY (idutente)
);

CREATE TABLE IF NOT EXISTS public.taxi
(
    targataxi character varying(6) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT taxi_pkey PRIMARY KEY (targataxi)
);

ALTER TABLE IF EXISTS public.pagamento
    ADD CONSTRAINT "FK_Pagamento_Prenotazione" FOREIGN KEY ("IDPrenotazione")
    REFERENCES public.prenotazione ("IDPrenotazione") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.prenotazione
    ADD CONSTRAINT idpasseggero FOREIGN KEY (idpasseggero)
    REFERENCES public.passeggero (idutente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.prenotazione
    ADD CONSTRAINT idtassista FOREIGN KEY (idtassista)
    REFERENCES public.tassista (idutente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.recensione
    ADD CONSTRAINT "FK_Recensione_Prenotazione" FOREIGN KEY ("IDPrenotazione")
    REFERENCES public.prenotazione ("IDPrenotazione") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tassista
    ADD CONSTRAINT tassista_targataxi_fkey FOREIGN KEY (targataxi)
    REFERENCES public.taxi (targataxi) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;