-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.erogatore
(
    "IDErogatore" serial NOT NULL,
    CONSTRAINT erogatore_pkey PRIMARY KEY ("IDErogatore")
);

CREATE TABLE IF NOT EXISTS public.fruitore
(
    "IDFruitore" serial NOT NULL,
    CONSTRAINT fruitore_pkey PRIMARY KEY ("IDFruitore")
);

CREATE TABLE IF NOT EXISTS public.pagamento
(
    "IDPagamento" serial NOT NULL,
    "IDPrenotazione" integer,
    "Importo" numeric(10, 2),
    "Stato" character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT pagamento_pkey PRIMARY KEY ("IDPagamento")
);

CREATE TABLE IF NOT EXISTS public.prenotazione
(
    "IDPrenotazione" serial NOT NULL,
    "DataOra" timestamp without time zone,
    "Stato" character varying(20) COLLATE pg_catalog."default",
    "IDFruitore" integer,
    "IDErogatore" integer,
    "IDTaxi" integer,
    CONSTRAINT prenotazione_pkey PRIMARY KEY ("IDPrenotazione")
);

CREATE TABLE IF NOT EXISTS public.recensione
(
    "IDRecensione" serial NOT NULL,
    "IDPrenotazione" integer,
    "Testo" text COLLATE pg_catalog."default",
    "Valutazione" integer,
    CONSTRAINT recensione_pkey PRIMARY KEY ("IDRecensione")
);

CREATE TABLE IF NOT EXISTS public.taxi
(
    "IDTaxi" serial NOT NULL,
    "Targa" character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT taxi_pkey PRIMARY KEY ("IDTaxi")
);

ALTER TABLE IF EXISTS public.pagamento
    ADD CONSTRAINT "FK_Pagamento_Prenotazione" FOREIGN KEY ("IDPrenotazione")
    REFERENCES public.prenotazione ("IDPrenotazione") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.prenotazione
    ADD CONSTRAINT "FK_Prenotazione_Erogatore" FOREIGN KEY ("IDErogatore")
    REFERENCES public.erogatore ("IDErogatore") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.prenotazione
    ADD CONSTRAINT "FK_Prenotazione_Fruitore" FOREIGN KEY ("IDFruitore")
    REFERENCES public.fruitore ("IDFruitore") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.prenotazione
    ADD CONSTRAINT "FK_Prenotazione_Taxi" FOREIGN KEY ("IDTaxi")
    REFERENCES public.taxi ("IDTaxi") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.recensione
    ADD CONSTRAINT "FK_Recensione_Prenotazione" FOREIGN KEY ("IDPrenotazione")
    REFERENCES public.prenotazione ("IDPrenotazione") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
